name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Check if PR is ready to merge
        run: |
          if [[ $(jq .pull_request.mergeable < $GITHUB_EVENT_PATH) == "true" ]]; then
            echo "Pull request is mergeable."
          else
            echo "Pull request is not mergeable."
            exit 1
          fi

      - name: Merge pull request
        if: success() && github.event.pull_request.mergeable == 'true'
        uses: peter-evans/merge-pull-request@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: 'merge'  # Options: 'merge', 'squash', 'rebase'
          commit-message: "Auto-merging pull request #${{ github.event.pull_request.number }}"
          token: ${{ secrets.GITHUB_TOKEN }}
